### ISSUE TITLE
Typo's and a minor question

### ISSUE THREAD

**Issue by dieterbong** [lamps-wg/csr-attestation#88]
When reviewing draft-ietf-lamps-csr-attestation-02 I noticed the following typo's:
section 4.3: ""TypedCert" is an ASN.1 construct that has the **charateristics** ..." 
section 6.1: "... certificate enrollments are often **asyncronous**, ..." 
section 8.1: "... **digitially** signed with ..." 
top of page 21: "...the shown Evidence, provides..." I would not put a comma here but I let a native speaker decide

And a question:
[I-D.tschofenig-rats-psa-token] refers to version 13 of this draft, but there is already a version 20. Should the csr-attestation draft point to version 20? Or to the latest version of rats-psa-token when finalizing the csr attestation draft?

Best regards,
Dieter

**Comment by ounsworth** [comment]
Thank you @dieterbong for catching the typos.

For the question:
In the source of the markdown, no version is referenced, so it must have been that -13 was current the last time we did a build and pushed to datatracker. If I build my local copy today then it references -20. Regardless, all this gets cleaned up in editor's queue anyway; id-tschofenig-rats-psa-token will need to be published an assigned an RFC number before it can be referenced by another RFC; the RFC editor takes care of publishing things in the correct order so that the cross-references work out cleanly.
